const LOCATIONS = [
  {
    county: 'Cook County',
    cities: [
      'Alsip', 'Arlington Heights', 'Barrington', 'Barrington Hills', 'Bartlett',
      'Bedford Park', 'Bellwood', 'Bensenville', 'Berkeley', 'Berwyn',
      'Blue Island', 'Bridgeview', 'Broadview', 'Brookfield', 'Buffalo Grove',
      'Burbank', 'Burnham', 'Burr Ridge', 'Calumet City', 'Calumet Park',
      'Chicago', 'Chicago Heights', 'Chicago Ridge', 'Cicero', 'Country Club Hills',
      'Countryside', 'Crestwood', 'Deer Park', 'Deerfield', 'Des Plaines',
      'Dixmoor', 'Dolton', 'East Dundee', 'East Hazel Crest', 'Elk Grove Village',
      'Elmhurst', 'Elmwood Park', 'Evanston', 'Evergreen Park', 'Flossmoor',
      'Ford Heights', 'Forest Park', 'Forest View', 'Frankfort', 'Franklin Park',
      'Glencoe', 'Glenview', 'Glenwood', 'Golf', 'Hanover Park',
      'Harvey', 'Harwood Heights', 'Hazel Crest', 'Hickory Hills', 'Hillside',
      'Hinsdale', 'Hodgkins', 'Hoffman Estates', 'Homer Glen', 'Hometown',
      'Homewood', 'Indian Head Park', 'Inverness', 'Justice', 'Kenilworth',
      'La Grange', 'La Grange Park', 'Lansing', 'Lemont', 'Lincolnwood',
      'Lynwood', 'Lyons', 'Markham', 'Matteson', 'Maywood',
      'McCook', 'Melrose Park', 'Merrionette Park', 'Midlothian', 'Morton Grove',
      'Mount Prospect', 'Niles', 'Norridge', 'North Riverside', 'Northbrook',
      'Northfield', 'Northlake', 'Oak Brook', 'Oak Forest', 'Oak Lawn',
      'Oak Park', 'Olympia Fields', 'Orland Hills', 'Orland Park', 'Palatine',
      'Palos Heights', 'Palos Hills', 'Palos Park', 'Park Forest', 'Park Ridge',
      'Phoenix', 'Posen', 'Prospect Heights', 'Richton Park', 'River Forest',
      'River Grove', 'Riverdale', 'Riverside', 'Robbins', 'Rolling Meadows',
      'Roselle', 'Rosemont', 'Sauk Village', 'Schaumburg', 'Schiller Park',
      'Skokie', 'South Barrington', 'South Chicago Heights', 'South Holland', 'Steger',
      'Stickney', 'Stone Park', 'Streamwood', 'Summit', 'Thornton',
      'Tinley Park', 'University Park', 'Westchester', 'Western Springs', 'Wheeling',
      'Willow Springs', 'Wilmette', 'Winnetka', 'Woodridge', 'Worth',
    ],
  },
  {
    county: 'DuPage County',
    cities: [
      'Addison', 'Aurora', 'Bartlett', 'Batavia', 'Bensenville',
      'Bloomingdale', 'Bolingbrook', 'Burr Ridge', 'Carol Stream', 'Clarendon Hills',
      'Darien', 'Downers Grove', 'Elk Grove Village', 'Elmhurst', 'Glen Ellyn',
      'Glendale Heights', 'Hanover Park', 'Hinsdale', 'Itasca', 'Lemont',
      'Lisle', 'Lombard', 'Naperville', 'Oak Brook', 'Oakbrook Terrace',
      'Roselle', 'Schaumburg', 'St. Charles', 'Villa Park', 'Warrenville',
      'Wayne', 'West Chicago', 'Westmont', 'Wheaton', 'Willowbrook',
      'Winfield', 'Wood Dale', 'Woodridge',
    ],
  },
  {
    county: 'Kane County',
    cities: [
      'Algonquin', 'Aurora', 'Barrington Hills', 'Bartlett', 'Batavia',
      'Big Rock', 'Burlington', 'Campton Hills', 'Carpentersville', 'East Dundee',
      'Elburn', 'Elgin', 'Geneva', 'Gilberts', 'Hampshire',
      'Hoffman Estates', 'Huntley', 'Kaneville', 'Lily Lake', 'Maple Park',
      'Montgomery', 'North Aurora', 'Pingree Grove', 'Sleepy Hollow', 'South Elgin',
      'St. Charles', 'Sugar Grove', 'Virgil', 'Wayne', 'West Dundee',
    ],
  },
  {
    county: 'Kendall County',
    cities: [
      'Aurora', 'Joliet', 'Lisbon', 'Millbrook', 'Millington',
      'Minooka', 'Montgomery', 'Newark', 'Oswego', 'Plainfield',
      'Plano', 'Plattville', 'Sandwich', 'Yorkville',
    ],
  },
  {
    county: 'Lake County',
    cities: [
      'Antioch', 'Arlington Heights', 'Bannockburn', 'Barrington', 'Barrington Hills',
      'Beach Park', 'Buffalo Grove', 'Deer Park', 'Deerfield', 'Fox Lake',
      'Fox River Grove', 'Grayslake', 'Green Oaks', 'Gurnee', 'Hainesville',
      'Hawthorn Woods', 'Highland Park', 'Highwood', 'Indian Creek', 'Island Lake',
      'Kildeer', 'Lake Barrington', 'Lake Bluff', 'Lake Forest', 'Lake Villa',
      'Lake Zurich', 'Lakemoor', 'Libertyville', 'Lincolnshire', 'Lindenhurst',
      'Long Grove', 'Mettawa', 'Mundelein', 'North Barrington', 'North Chicago',
      'Old Mill Creek', 'Palatine', 'Park City', 'Port Barrington', 'Riverwoods',
      'Round Lake', 'Round Lake Beach', 'Round Lake Heights', 'Round Lake Park',
      'Third Lake', 'Tower Lakes', 'Vernon Hills', 'Volo', 'Wadsworth',
      'Wauconda', 'Waukegan', 'Wheeling', 'Winthrop Harbor', 'Zion',
    ],
  },
  {
    county: 'McHenry County',
    cities: [
      'Algonquin', 'Barrington Hills', 'Bull Valley', 'Cary', 'Crystal Lake',
      'Fox Lake', 'Fox River Grove', 'Greenwood', 'Harvard', 'Hebron',
      'Holiday Hills', 'Huntley', 'Island Lake', 'Johnsburg', 'Lake in the Hills',
      'Lakemoor', 'Lakewood', 'Marengo', 'McCullom Lake', 'McHenry',
      'Oakwood Hills', 'Port Barrington', 'Prairie Grove', 'Richmond', 'Ringwood',
      'Spring Grove', 'Trout Valley', 'Union', 'Wonder Lake', 'Woodstock',
    ],
  },
  {
    county: 'Will County',
    cities: [
      'Aurora', 'Beecher', 'Bolingbrook', 'Braceville', 'Braidwood',
      'Channahon', 'Coal City', 'Crest Hill', 'Crete', 'Diamond',
      'Elwood', 'Frankfort', 'Homer Glen', 'Joliet', 'Lemont',
      'Lockport', 'Manhattan', 'Minooka', 'Mokena', 'Monee',
      'Naperville', 'New Lenox', 'Orland Park', 'Park Forest', 'Peotone',
      'Plainfield', 'Rockdale', 'Romeoville', 'Shorewood', 'Steger',
      'Symerton', 'Tinley Park', 'University Park', 'Wilmington', 'Woodridge',
    ],
  },
];

export default LOCATIONS;
